config/routes.rb
  Rails.application.routes.draw do
  get 'auth/google_oauth2/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/about' => 'welcome_page#about', as: :about

  root 'welcome_page#index'

  get '/search' => 'welcome_page#search', as: :search

  resources :games
  resources :users

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	belongs_to :user
	belongs_to :favoritible, polymorphic: :true
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :participations
  has_many :moves
  has_many :players, through: :participations
  has_many :favorites, as: :favoritible
end

app/models/move.rb
class Move < ActiveRecord::Base
  belongs_to :game
  has_many :favorites, as: :favoritible
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :player
  belongs_to :game
end

app/models/player.rb
class Player < ActiveRecord::Base
	has_many :participations
	has_many :games, through: :participations
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :favorites

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.email = auth['info']['email']
      user.name = auth['info']['name']
      user.uid = auth['uid']
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
    @cols = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
    @rows = (1..8).to_a.reverse.each { |e| e.to_s }
    @moves = @game.moves
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth['provider'], auth['uid']) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to user_path(user)
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(session[:user_id])
  end
end

app/controllers/welcome_page_controller.rb
class WelcomePageController < ApplicationController
  def index
  end

  def show
  end

  def search
    @search = Game.search do
      fulltext params[:search]
    end
    @results = @search.results
    p params[:search]
    p @search
    p @results
    @test = "I am here"
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_page_helper.rb
module WelcomePageHelper
end

app/views/games/index.html.erb
<div class="user_landing">
  <div class="all_games">
    <h2>View a Game</h2>
    <% @games.each do |g| %>
      <ul>
        <li><%= link_to g.event, game_path(g.id) %>, Date: <%=g.date_played %>, ECO Code: <%= g.eco_code %></li>
      </ul>
    <% end %>
  </div>
</div>

app/views/games/show.html.erb
<div class='user_landing show_game_border'>

  <div class='columns_for_chess_board buttons_for_chess_board'>
  <input type='submit' value='Previous' class='btns'>

  <input name='current_move' type='hidden' value='0'>
  <input type='submit' value='Next' id='next-btn' class='btns'>
  <input name='total_moves' type='hidden' value='<%= @moves.count %>'>
  <div class= 'fav_and_jump_div'>
    <input id='move_count' type='text'>
    <input type='submit' value='Go!'>
    <input id='play' type='submit' value='Play'>
    <input id='stop' type='submit' value='Stop'>
  <div>

  <a class='move' id='0' href='rnbqkbnrpppppppp00000000000000000000000000000000PPPPPPPPRNBQKBNR'>Reset Board</a>
  </div>
</div>
  </div>

<div class='board_div columns_for_chess_board'>
  <table class='chess-board'>
    <% @rows.each_with_index do |r, i| %>
      <tr>
        <% @cols.each_with_index do |col, ind| %>
          <td id='<%=col%><%=r%>'></td>
        <%end%>
      </tr>
    <%end%>
  </table>

</div>

<div class='fen_list columns_for_chess_board'>
  <table>

  <% @moves.each_slice(2) do |move| %>
    <tr>
      <td>
        <a class='move' id='<%= move[0].iteration %>' href='<%= move[0].board_position %>'><%= move[0].notation %></a>
      </td>
      <td>
        <a class='move' id='<%= move[1].iteration %>' href='<%= move[1].board_position %>'><%= move[1].notation %></a>
      </td>
    <tr>
  <% end %>
  </table>
</div>

</div>

app/views/layouts/_header.html.erb
 <div class= 'fixed_header'>
<nav>
  <ul>
    <li class='left-nav' id='home_icon'>
      <%= link_to 'चतुरङ्ग', root_path %>
    </li>
    <li class='left-nav'>
      <%= link_to 'chess is', about_path %>
    </li>
    <li class='left-nav'>
      <%= link_to 'explore games', games_path %>
    </li>
    <li class='left-nav'>
      <% num = Game.count %>
      <% rand = (1..num).to_a.sample %>
      <%= link_to 'random game', "/games/#{rand}" %>
    </li>

      <% if session[:user_id].nil? %>
      <li class='left-nav'>
        <%= link_to 'login', '/auth/google_oauth2' %>
      </li>
      <% else %>
      <li class='left-nav'>
      <%= link_to 'dashboard', user_path(User.find(session[:user_id])) %>
      </li>
        <li class='left-nav'>
        <%= link_to 'logout', '/logout' %>
      </li>


      <% end %>

    <li class='right-nav'>
      <div id="search">
            <%= form_tag '/search', :method => 'get' do %>
            <%= text_field_tag :search, params[:search], :id => 'search_field' %>
            <%= submit_tag "Search", :name => nil %>
            <% end %>
      </div>
    </li>
  </ul>

</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chaturanga Chess</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Roboto:100' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div id='container_wrapper'>
    <%= yield %>
  </div>
</body>
</html>

app/views/users/show.html.erb
<div class='user_landing'>
  <div class='user-name' id='my_name'>
    <h1>hi <%=@user.name%></h1>
  </div>
  <div class='user-info_div' id='scroll'>

    <div id='fav_games_div'>
      <h3>your favorite games</h3>
      <table id='fav_games'>
        <p>
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
<p>
It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>


<p>
Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>

<p>
The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>
<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>
      </table>
    </div>

    <div id='fav_games_div'>
        <h3>your favorite moves</h3>
        <table id='fav_moves'>
        </table>
    </div>

  </div>
</div>

app/views/welcome_page/about.html.erb
<div class='user_landing'>
  <div class='user-name' id='my_name'>
    <h1>chess is what?</h1>
  </div>
  <div class='user-info_div' id='scroll'>

    <div id='fav_games_div'>
      <h3>history</h3>
      <table id='fav_games'>
        <p>
<p>Chess is a two-player strategy board game played on a chessboard, a checkered gameboard with 64 squares arranged in an eight-by-eight grid. It is one of the world's most popular games, played by millions of people worldwide in homes, parks, clubs, online, by correspondence, and in tournaments.

<p>Each player begins the game with 16 pieces: one king, one queen, two rooks, two knights, two bishops, and eight pawns. Each of the six piece types moves differently. Pieces are used to attack and capture the opponent's pieces, with the objective to 'checkmate' the opponent's king by placing it under an inescapable threat of capture. In addition to checkmate, the game can be won by the voluntary resignation of the opponent, which typically occurs when too much material is lost, or if checkmate appears unavoidable. A game may also result in a draw in several ways, where neither player wins. The course of the game is divided into three phases: opening, middlegame, and endgame.

<p>The first official World Chess Champion, Wilhelm Steinitz, claimed his title in 1886; the current World Champion is Norwegian chess Grandmaster Magnus Carlsen. In addition to the World Championship, there are the Women's World Championship, the Junior World Championship, the World Senior Championship, the Correspondence Chess World Championship, the World Computer Chess Championship, and Blitz and Rapid World Championships. The Chess Olympiad is a popular competition among teams from different nations. Online chess has opened amateur and professional competition to a wide and varied group of players. Chess is a recognized sport of the International Olympic Committee and international chess competition is sanctioned by the World Chess Federation (FIDE), which adopted the now-standard Staunton chess set in 1924 for use in all official games. There are also many chess variants, with different rules, different pieces, and different boards.

<p>Since the second half of the 20th century, computers have been programmed to play chess with increasing success, to the point where the strongest home computers play chess at a higher level than the best human players. In the past two decades computer analysis has contributed significantly to chess theory, particularly in the endgame. The computer Deep Blue was the first machine to overcome a reigning World Chess Champion in a match when it defeated Garry Kasparov in 1997.</p>
<p>
  </table>
    </div>

    <div id='fav_games_div'>
        <h3>piece movements</h3>
        <table id='fav_moves'>
          <p>
<p>White always moves first. After the first move, players alternately move one piece per turn (except for castling, when two pieces are moved). Pieces are moved to either an unoccupied square or one occupied by an opponent's piece, which is captured and removed from play. With the sole exception of en passant, all pieces capture opponent's pieces by moving to the square that the opponent's piece occupies. A player may not make any move that would put or leave his or her king under attack. If the player to move has no legal moves, the game is over; it is either a checkmate (a loss for the player with no legal moves) if the king is under attack, or a stalemate (a draw) if the king is not.

<p>Each chess piece has its own style of moving. In the diagrams, the dots mark the squares where the piece can move if no other pieces (including one's own piece) are on the squares between the piece's initial position and its destination.
<p>
<ul>
<li>The king moves one square in any direction. The king has also a special move which is called castling and involves also moving a rook.
<li>The rook can move any number of squares along any rank or file, but may not leap over other pieces. Along with the king, the rook is involved during the king's castling move.
<li>The bishop can move any number of squares diagonally, but may not leap over other pieces.
<li>The queen combines the power of the rook and bishop and can move any number of squares along rank, file, or diagonal, but it may not leap over other pieces.
<li>The knight moves to any of the closest squares that are not on the same rank, file, or diagonal, thus the move forms an "L"-shape: two squares vertically and one square horizontally, or two squares horizontally and one square vertically. The knight is the only piece that can leap over other pieces.
<li>The pawn may move forward to the unoccupied square immediately in front of it on the same file, or on its first move it may advance two squares along the same file provided both squares are unoccupied (black "●"s in the diagram); or the pawn may capture an opponent's piece on a square diagonally in front of it on an adjacent file, by moving to that square (black "x"s). The pawn has two special moves: the en passant capture and pawn promotion.
</ul></p>
        </table>
    </div>

  </div>
</div>

app/views/welcome_page/index.html.erb
<div id='wrapper'>
<h1 id='title'>Chaturanga Ch<span id='e6'>e6</span>s</h1>

<h1 id='san_title'>चतुरङ्ग</h1>
<h5 id='subheader'>trace beautiful moves from the past</h5>

</div>

<div id='signup'>

</div>

app/views/welcome_page/search.html.erb
<div class='user_landing'>
  <div class='search_result'>
    <h2>Search Results</h2>
    <% @results.each do |r| %>
      <ul>
        <li><%= link_to r.event, game_path(r.id) %>, Date: <%=r.date_played %>, ECO Code: <%= r.eco_code %></li>
      </ul>
    <% end %>
  </div>
</div>